export interface PlanetStat {
  value: string
  label: string
}

export interface MoonData {
  size: number
  orbit: number
  speed: number
}

export interface PlanetData {
  name: string
  type: string
  orbit: number
  size: number
  speed: number
  offset: number
  desc: string
  longDesc: string
  stats: PlanetStat[]
  rings?: boolean
  moon?: MoonData
  color: string
  textureUrl: string
  /** Excentricidad orbital real (0 = círculo perfecto). Valores reales de la NASA,
   *  usados en la fórmula polar r(θ) = a(1-e²)/(1+e·cosθ) con el Sol en el foco. */
  eccentricity: number
}

export const planets: PlanetData[] = [
  {
    name: 'Mercurio',

    type: 'PLANETA ROCOSO',
    orbit: 5.5,
    size: 0.3,
    speed: 0.35,
    offset: 0,
    color: '#A0937E',
    textureUrl: '/textures/2k_mercury.jpg',
    eccentricity: 0.206,
    desc: 'El planeta más pequeño y cercano al Sol.',
    longDesc: 'Mercurio es el planeta más pequeño del sistema solar y el más cercano al Sol. Su superficie está cubierta de cráteres. No tiene atmósfera significativa, causando temperaturas extremas: 430°C de día y -180°C de noche.',
    stats: [
      { value: '0.39 UA', label: 'Distancia al Sol' },
      { value: '88 días', label: 'Año orbital' },
      { value: '4,879 km', label: 'Diámetro' },
      { value: '430°C / -180°C', label: 'Temperatura' },
      { value: '0.38g', label: 'Gravedad' },
      { value: '0', label: 'Lunas' },
    ],
  },
  {
    name: 'Venus',

    type: 'PLANETA ROCOSO',
    orbit: 8,
    size: 0.55,
    speed: 0.25,
    offset: 1.2,
    color: '#E8C080',
    textureUrl: '/textures/4k_venus_atmosphere.jpg',
    eccentricity: 0.007,
    desc: 'El planeta más caliente con atmósfera densa.',
    longDesc: 'Venus es el planeta más caliente del sistema solar. Su densa atmósfera de CO2 atrapa el calor hasta 462°C. Gira en sentido contrario al resto de planetas y un día venusino dura más que su año.',
    stats: [
      { value: '0.72 UA', label: 'Distancia al Sol' },
      { value: '225 días', label: 'Año orbital' },
      { value: '12,104 km', label: 'Diámetro' },
      { value: '462°C', label: 'Temperatura' },
      { value: '0.91g', label: 'Gravedad' },
      { value: '0', label: 'Lunas' },
    ],
  },
  {
    name: 'Tierra',

    type: 'PLANETA ROCOSO',
    orbit: 11.5,
    size: 0.6,
    speed: 0.2,
    offset: 2.5,
    color: '#4A90D9',
    textureUrl: '/textures/8k_earth_daymap.jpg',
    eccentricity: 0.017,
    desc: 'Nuestro hogar. El único planeta con vida conocida.',
    longDesc: 'La Tierra es el tercer planeta del sistema solar y el único conocido que alberga vida. Con un 71% de su superficie cubierta por océanos, su campo magnético y atmósfera rica en oxígeno protegen toda forma de vida conocida.',
    stats: [
      { value: '1.00 UA', label: 'Distancia al Sol' },
      { value: '365.25 días', label: 'Año orbital' },
      { value: '12,742 km', label: 'Diámetro' },
      { value: '15°C', label: 'Temp. media' },
      { value: '1.0g', label: 'Gravedad' },
      { value: '1', label: 'Lunas' },
    ],
    moon: { size: 0.15, orbit: 1.5, speed: 0.8 },
  },
  {
    name: 'Marte',

    type: 'PLANETA ROCOSO',
    orbit: 16,
    size: 0.45,
    speed: 0.15,
    offset: 3.8,
    color: '#D07040',
    textureUrl: '/textures/8k_mars.jpg',
    eccentricity: 0.093,
    desc: 'El planeta rojo. Objetivo de exploración humana.',
    longDesc: 'Marte es conocido como el planeta rojo por el óxido de hierro en su superficie. Posee el volcán más grande del sistema solar, Olympus Mons, y el cañón Valles Marineris. Evidencias sugieren que tuvo agua líquida en el pasado.',
    stats: [
      { value: '1.52 UA', label: 'Distancia al Sol' },
      { value: '687 días', label: 'Año orbital' },
      { value: '6,779 km', label: 'Diámetro' },
      { value: '-60°C', label: 'Temp. media' },
      { value: '0.38g', label: 'Gravedad' },
      { value: '2', label: 'Lunas' },
    ],
  },
  {
    name: 'Júpiter',

    type: 'GIGANTE GASEOSO',
    orbit: 24,
    size: 1.4,
    speed: 0.08,
    offset: 0.8,
    color: '#C88B60',
    textureUrl: '/textures/8k_jupiter.jpg',
    eccentricity: 0.048,
    desc: 'El gigante del sistema solar. La Gran Mancha Roja.',
    longDesc: 'Júpiter es el planeta más grande del sistema solar, con masa mayor que todos los demás planetas juntos. Su Gran Mancha Roja es una tormenta activa por más de 350 años. Posee 95 lunas, entre ellas Ganímedes, la luna más grande del sistema solar.',
    stats: [
      { value: '5.20 UA', label: 'Distancia al Sol' },
      { value: '11.9 años', label: 'Año orbital' },
      { value: '139,820 km', label: 'Diámetro' },
      { value: '-110°C', label: 'Temp. nubes' },
      { value: '2.53g', label: 'Gravedad' },
      { value: '95', label: 'Lunas' },
    ],
    moon: { size: 0.1, orbit: 2.2, speed: 0.55 },
  },
  {
    name: 'Saturno',

    type: 'GIGANTE GASEOSO',
    orbit: 32,
    size: 1.5,
    speed: 0.055,
    offset: 3.2,
    rings: true,
    color: '#F0D8A8',
    textureUrl: '/textures/8k_saturn.jpg',
    eccentricity: 0.056,
    desc: 'Famoso por sus espectaculares anillos de hielo.',
    longDesc: 'Saturno es reconocido por sus impresionantes anillos de hielo y roca. Es el segundo planeta más grande y tiene una densidad tan baja que flotaría en el agua. Su luna Titán tiene una atmósfera densa y lagos de metano líquido.',
    stats: [
      { value: '9.54 UA', label: 'Distancia al Sol' },
      { value: '29.5 años', label: 'Año orbital' },
      { value: '116,460 km', label: 'Diámetro' },
      { value: '-140°C', label: 'Temp. nubes' },
      { value: '1.07g', label: 'Gravedad' },
      { value: '146', label: 'Lunas' },
    ],
  },
  {
    name: 'Urano',

    type: 'GIGANTE DE HIELO',
    orbit: 40,
    size: 1.1,
    speed: 0.035,
    offset: 2.1,
    color: '#7BCAE0',
    textureUrl: '/textures/2k_uranus.jpg',
    eccentricity: 0.046,
    desc: 'El planeta inclinado. Rota de lado.',
    longDesc: 'Urano es un gigante de hielo con su eje inclinado casi 98°, por lo que ruede de lado alrededor del Sol. Su atmósfera de metano le da su color azul-verdoso característico. Tiene 27 lunas conocidas y un sistema de anillos débiles.',
    stats: [
      { value: '19.2 UA', label: 'Distancia al Sol' },
      { value: '84 años', label: 'Año orbital' },
      { value: '51,118 km', label: 'Diámetro' },
      { value: '-195°C', label: 'Temp. nubes' },
      { value: '0.89g', label: 'Gravedad' },
      { value: '27', label: 'Lunas' },
    ],
  },
  {
    name: 'Neptuno',

    type: 'GIGANTE DE HIELO',
    orbit: 48,
    size: 0.95,
    speed: 0.025,
    offset: 0.7,
    color: '#4080D0',
    textureUrl: '/textures/2k_neptune.jpg',
    eccentricity: 0.010,
    desc: 'El más lejano. Vientos de 2,100 km/h.',
    longDesc: 'Neptuno es el planeta más lejano del sistema solar con los vientos más rápidos: hasta 2,100 km/h. Su color azul intenso se debe al metano en su atmósfera. Posee 16 lunas conocidas, siendo Tritón la más grande.',
    stats: [
      { value: '30.1 UA', label: 'Distancia al Sol' },
      { value: '165 años', label: 'Año orbital' },
      { value: '49,528 km', label: 'Diámetro' },
      { value: '-200°C', label: 'Temp. nubes' },
      { value: '1.14g', label: 'Gravedad' },
      { value: '16', label: 'Lunas' },
    ],
  },
]

export interface ConstellationData {
  name: string
  alias: string
  type: 'zodiacal' | 'boreal' | 'austral' | 'custom'
  desc: string
  figure: string
  stars: [number, number][]
  lines: [number, number][]
}

export const constellations: ConstellationData[] = [
  // �"?�"? ZODIACALES �"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?
  { name:'Aries', alias:'El Carnero', type:'zodiacal', figure:'Un carnero con cuernos dorados',
    desc:'Primera constelación del zodiaco. Aunque pequeña, el punto vernal �?"donde el Sol cruza el ecuador celeste�?" se ubica aquí.',
    stars:[[0.07,0.30],[0.09,0.31],[0.11,0.30],[0.12,0.28]], lines:[[0,1],[1,2],[2,3]] },
  { name:'Tauro', alias:'El Toro', type:'zodiacal', figure:'Un toro fiero con cuernos apuntando al cielo',
    desc:'Alberga las Pléyades y las Híades, los cúmulos estelares más famosos. Aldebaran, su estrella principal, es el ojo del toro.',
    stars:[[0.15,0.35],[0.17,0.33],[0.19,0.31],[0.20,0.33],[0.18,0.36],[0.16,0.37],[0.21,0.29],[0.23,0.27]], lines:[[0,1],[1,2],[2,3],[3,4],[4,5],[5,0],[2,6],[6,7]] },
  { name:'Géminis', alias:'Los Gemelos', type:'zodiacal', figure:'Dos hermanos de pie tomados del brazo',
    desc:'Representada por Cástor y Pólux, los gemelos mitológicos hijos de Zeus. Cástor es en realidad un sexteto estelar.',
    stars:[[0.09,0.28],[0.11,0.32],[0.07,0.34],[0.13,0.36],[0.09,0.38],[0.12,0.40]], lines:[[0,1],[0,2],[1,3],[2,4],[3,5],[4,5]] },
  { name:'Cáncer', alias:'El Cangrejo', type:'zodiacal', figure:'Un cangrejo de mar con tenazas abiertas',
    desc:'La constelación más débil del zodiaco. Alberga Praesepe, conocido como el "Enjambre de Abejas", un brillante cúmulo abierto.',
    stars:[[0.30,0.38],[0.32,0.36],[0.34,0.38],[0.32,0.41],[0.30,0.40]], lines:[[0,1],[1,2],[2,3],[3,4],[4,0],[1,3]] },
  { name:'Leo', alias:'El León', type:'zodiacal', figure:'Un león majestuoso reclinado mirando al horizonte',
    desc:'Constelación zodiacal prominente. Regulus, su estrella alfa, es la más cercana a la eclíptica de todas las estrellas brillantes.',
    stars:[[0.20,0.48],[0.22,0.44],[0.25,0.42],[0.28,0.43],[0.30,0.40],[0.23,0.50],[0.27,0.53],[0.30,0.51]], lines:[[0,1],[1,2],[2,3],[3,4],[0,5],[5,6],[6,7],[7,3]] },
  { name:'Virgo', alias:'La Doncella', type:'zodiacal', figure:'Una doncella celeste sosteniendo una espiga de trigo',
    desc:'La más grande del zodiaco. Spica es su estrella más brillante, una binaria eclipsante. El Cúmulo de Virgo contiene más de 1300 galaxias.',
    stars:[[0.50,0.42],[0.52,0.44],[0.54,0.43],[0.53,0.47],[0.51,0.49],[0.56,0.46],[0.55,0.50]], lines:[[0,1],[1,2],[2,3],[3,4],[4,0],[2,5],[3,6],[5,6]] },
  { name:'Libra', alias:'La Balanza', type:'zodiacal', figure:'Una balanza de justicia equilibrada en el cosmos',
    desc:'La única constelación del zodiaco que representa un objeto inanimado. Sus estrellas principales tienen nombres árabes que significan "garras del escorpión".',
    stars:[[0.60,0.46],[0.62,0.44],[0.64,0.46],[0.63,0.49],[0.61,0.49]], lines:[[0,1],[1,2],[2,3],[3,4],[4,0],[1,3]] },
  { name:'Escorpio', alias:'El Escorpión', type:'zodiacal', figure:'Un escorpión con cola curvada y aguijón amenazante',
    desc:'Destaca por Antares, supergigante roja en su corazón. Su cola curvada es inconfundible en noches de verano del hemisferio sur.',
    stars:[[0.62,0.50],[0.64,0.52],[0.66,0.55],[0.65,0.58],[0.63,0.61],[0.60,0.63],[0.58,0.62],[0.57,0.59]], lines:[[0,1],[1,2],[2,3],[3,4],[4,5],[5,6],[6,7]] },
  { name:'Sagitario', alias:'El Arquero', type:'zodiacal', figure:'Un centauro arquero apuntando al centro de la galaxia',
    desc:'Apunta hacia el centro de la Vía Láctea. Contiene más nebulosas y cúmulos que cualquier otra constelación del zodiaco.',
    stars:[[0.52,0.65],[0.54,0.62],[0.56,0.64],[0.55,0.68],[0.57,0.67],[0.53,0.70],[0.58,0.70]], lines:[[0,1],[1,2],[2,4],[0,3],[3,5],[4,6],[3,4]] },
  { name:'Capricornio', alias:'La Cabra Marina', type:'zodiacal', figure:'Una criatura mítica mitad cabra mitad pez',
    desc:'Una de las constelaciones más antiguas. En ella se encuentra el solsticio de invierno en las culturas antiguas. Sus estrellas son relativamente tenues.',
    stars:[[0.80,0.56],[0.82,0.54],[0.84,0.55],[0.83,0.58],[0.81,0.59],[0.85,0.57]], lines:[[0,1],[1,2],[2,3],[3,4],[4,0],[2,5],[5,3]] },
  { name:'Acuario', alias:'El Portador de Agua', type:'zodiacal', figure:'Una figura vertiendo agua de un cántaro celestial',
    desc:'Una de las constelaciones más antiguas, conocida desde Babilonia. Los sumerios la asociaban con su dios del agua Ea.',
    stars:[[0.15,0.62],[0.17,0.65],[0.19,0.63],[0.18,0.68],[0.20,0.67],[0.16,0.70]], lines:[[0,1],[0,2],[1,3],[2,4],[3,5],[1,2]] },
  { name:'Piscis', alias:'Los Peces', type:'zodiacal', figure:'Dos peces nadando en direcciones opuestas',
    desc:'�sltima constelación del zodiaco. El punto vernal ha migrado aquí desde Aries debido a la precesión de los equinoccios.',
    stars:[[0.03,0.44],[0.05,0.42],[0.06,0.44],[0.04,0.47],[0.07,0.47],[0.02,0.50],[0.04,0.51]], lines:[[0,1],[1,2],[2,3],[3,0],[2,4],[3,5],[5,6],[6,0]] },

  // �"?�"? BOREALES �"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?
  { name:'Orión', alias:'El Cazador', type:'boreal', figure:'Un guerrero con cinturón de tres estrellas y espada',
    desc:'La más reconocible del cielo. Sus tres estrellas del cinturón (Alnitak, Alnilam, Mintaka) son visibles desde todo el planeta.',
    stars:[[0.28,0.22],[0.26,0.28],[0.27,0.30],[0.29,0.30],[0.31,0.28],[0.27,0.35],[0.29,0.35],[0.25,0.38],[0.28,0.42],[0.30,0.44],[0.27,0.48],[0.32,0.46]], lines:[[0,1],[1,2],[2,3],[3,4],[4,0],[2,6],[3,6],[6,7],[6,8],[8,9],[8,10],[9,11]] },
  { name:'Osa Mayor', alias:'La Osa Grande', type:'boreal', figure:'Un gran oso celeste con cola extendida hacia el norte',
    desc:'Las siete estrellas del Carro sirven para localizar la estrella Polar. Es la tercera constelación más grande del cielo.',
    stars:[[0.42,0.18],[0.45,0.20],[0.44,0.23],[0.40,0.25],[0.38,0.27],[0.42,0.29],[0.46,0.28]], lines:[[0,1],[1,2],[2,3],[3,4],[4,5],[5,6],[6,2]] },
  { name:'Osa Menor', alias:'La Osa Pequeña', type:'boreal', figure:'Una osa pequeña con Polaris en la punta de su cola',
    desc:'Contiene Polaris, la estrella Polar, a menos de 1° del polo norte celeste. Polaris es en realidad un sistema estelar triple.',
    stars:[[0.52,0.06],[0.54,0.09],[0.51,0.12],[0.48,0.13],[0.47,0.10],[0.49,0.08],[0.53,0.13]], lines:[[0,1],[1,2],[2,3],[3,4],[4,5],[5,0],[2,6],[3,6]] },
  { name:'Casiopea', alias:'La Reina', type:'boreal', figure:'Una reina sentada en su trono formando una W',
    desc:'Reconocible por su forma de W o M. Visible todo el año desde el hemisferio norte, circumpolar desde latitudes mayores a 34°.',
    stars:[[0.70,0.20],[0.73,0.24],[0.76,0.21],[0.79,0.25],[0.82,0.22]], lines:[[0,1],[1,2],[2,3],[3,4]] },
  { name:'Perseo', alias:'El Héroe', type:'boreal', figure:'Un héroe sosteniendo la cabeza de Medusa',
    desc:'Contiene Algol, "la estrella del demonio", una binaria eclipsante que cambia de brillo cada 2.87 días. Perseo rescató a Andrómeda.',
    stars:[[0.14,0.20],[0.16,0.17],[0.18,0.19],[0.17,0.22],[0.15,0.24],[0.19,0.24],[0.20,0.21]], lines:[[0,1],[1,2],[2,3],[3,4],[4,0],[2,5],[3,5],[5,6]] },
  { name:'Auriga', alias:'El Cochero', type:'boreal', figure:'Un cochero sosteniendo una cabra y sus cabrillas',
    desc:'Contiene Capella, la sexta estrella más brillante del cielo. También alberga tres brillantes cúmulos abiertos visibles con binoculares.',
    stars:[[0.22,0.18],[0.24,0.15],[0.27,0.17],[0.27,0.21],[0.24,0.23],[0.21,0.21]], lines:[[0,1],[1,2],[2,3],[3,4],[4,5],[5,0],[0,4]] },
  { name:'Hércules', alias:'El Héroe Griego', type:'boreal', figure:'Un héroe arrodillado con maza y piel de león',
    desc:'Cuarta constelación más grande del cielo. Alberga M13, el Gran Cúmulo Globular de Hércules, visible a simple vista bajo cielos oscuros.',
    stars:[[0.67,0.26],[0.69,0.24],[0.71,0.26],[0.70,0.29],[0.68,0.30],[0.72,0.29],[0.68,0.33],[0.71,0.33]], lines:[[0,1],[1,2],[2,3],[3,4],[4,0],[3,5],[4,6],[5,7],[6,7]] },
  { name:'Boyero', alias:'El Pastor de Bueyes', type:'boreal', figure:'Un pastor sujetando a los perros de caza',
    desc:'Contiene Arturo, la estrella más brillante del hemisferio norte y la cuarta más brillante del cielo total, una gigante naranja.',
    stars:[[0.58,0.30],[0.60,0.27],[0.62,0.29],[0.61,0.33],[0.59,0.35],[0.63,0.32]], lines:[[0,1],[1,2],[2,3],[3,4],[4,0],[2,5],[3,5]] },
  { name:'Corona Boreal', alias:'La Corona del Norte', type:'boreal', figure:'Una corona semicircular de gemas celestiales',
    desc:'Pequeña pero perfecta semicircunferencia de estrellas. Alphecca, su estrella más brillante, es un sistema binario eclipsante.',
    stars:[[0.63,0.30],[0.64,0.28],[0.66,0.27],[0.68,0.28],[0.69,0.30],[0.67,0.32],[0.65,0.32]], lines:[[0,1],[1,2],[2,3],[3,4],[4,5],[5,6],[6,0]] },
  { name:'Dragón', alias:'El Gran Dragón', type:'boreal', figure:'Un enorme dragón enroscado alrededor del polo norte',
    desc:'Una de las constelaciones más largas. Thuban, en su cola, fue la estrella polar hace 5000 años en tiempos de los faraones egipcios.',
    stars:[[0.62,0.08],[0.65,0.10],[0.67,0.08],[0.66,0.05],[0.69,0.12],[0.71,0.10],[0.70,0.14],[0.68,0.16]], lines:[[0,1],[1,2],[2,3],[3,0],[1,4],[4,5],[5,6],[6,7],[7,2]] },
  { name:'Lira', alias:'La Lira de Orfeo', type:'boreal', figure:'Una lira musical del poeta Orfeo',
    desc:'Contiene Vega, quinta estrella más brillante del cielo y parte del Triángulo de Verano. Vega fue la estrella polar hace 14,000 años.',
    stars:[[0.35,0.12],[0.33,0.16],[0.37,0.16],[0.34,0.19],[0.36,0.19]], lines:[[0,1],[0,2],[1,3],[2,4],[3,4]] },
  { name:'Cisne', alias:'El Gran Cisne', type:'boreal', figure:'Un cisne volando con alas extendidas hacia el sur',
    desc:'Contiene Deneb y forma la Cruz del Norte. Cygnus X-1, en su interior, fue el primer candidato a agujero negro identificado en 1972.',
    stars:[[0.75,0.18],[0.76,0.21],[0.77,0.24],[0.74,0.22],[0.78,0.22],[0.76,0.26],[0.76,0.28]], lines:[[0,1],[1,2],[1,3],[1,4],[2,5],[5,6]] },
  { name:'Águila', alias:'El Águila Imperial', type:'boreal', figure:'Un águila en vuelo con Altair en su pecho',
    desc:'Altair, su estrella principal, rota tan rápido que su diámetro ecuatorial es 20% mayor que el polar. Forma el Triángulo de Verano.',
    stars:[[0.74,0.44],[0.76,0.42],[0.78,0.44],[0.76,0.47],[0.74,0.49],[0.78,0.49]], lines:[[0,1],[1,2],[2,3],[3,4],[4,0],[1,3]] },
  { name:'Andrómeda', alias:'La Princesa Encadenada', type:'boreal', figure:'Una princesa encadenada a las rocas del mar',
    desc:'Alberga M31, la galaxia de Andrómeda, el objeto más lejano visible a simple vista, a 2.537 millones de años luz.',
    stars:[[0.86,0.30],[0.88,0.33],[0.90,0.36],[0.92,0.34],[0.91,0.38]], lines:[[0,1],[1,2],[1,3],[2,4]] },
  { name:'Pegaso', alias:'El Caballo Alado', type:'boreal', figure:'Un caballo blanco con alas que vuela por el cosmos',
    desc:'El Gran Cuadrado de Pegaso es un asterismo famoso. Contiene 51 Pegasi, primera estrella parecida al Sol con exoplaneta confirmado.',
    stars:[[0.88,0.40],[0.91,0.40],[0.91,0.43],[0.88,0.43],[0.93,0.38],[0.94,0.42],[0.92,0.46]], lines:[[0,1],[1,2],[2,3],[3,0],[1,4],[4,5],[5,6],[6,2]] },
  { name:'Cefeo', alias:'El Rey Etiope', type:'boreal', figure:'Un rey con corona y cetro en el norte celeste',
    desc:'Contiene VV Cephei, una de las estrellas más grandes conocidas, y Mu Cephei, "la estrella granate de Herschel", de intenso color rojo.',
    stars:[[0.83,0.10],[0.85,0.07],[0.87,0.10],[0.87,0.14],[0.85,0.16],[0.83,0.14]], lines:[[0,1],[1,2],[2,3],[3,4],[4,5],[5,0],[0,3]] },
  { name:'Jirafa', alias:'La Jirafa Celeste', type:'boreal', figure:'Una jirafa con cuello largo hacia el polo norte',
    desc:'La quinta constelación más grande pero muy tenue; ninguna de sus estrellas supera magnitud 4. Ocupa un gran área circumpolar.',
    stars:[[0.18,0.08],[0.20,0.06],[0.22,0.08],[0.21,0.12],[0.19,0.14],[0.23,0.14]], lines:[[0,1],[1,2],[2,3],[3,4],[4,0],[2,5],[3,5]] },
  { name:'Lacerta', alias:'El Lagarto', type:'boreal', figure:'Un pequeño lagarto zigzagueando entre las estrellas',
    desc:'Pequeña constelación introducida por Johannes Hevelius en 1687. Contiene BL Lacertae, prototipo de una clase especial de galaxias activas.',
    stars:[[0.84,0.26],[0.85,0.28],[0.83,0.30],[0.85,0.32],[0.87,0.30]], lines:[[0,1],[1,2],[2,3],[3,4],[4,1]] },
  { name:'Serpiente', alias:'La Gran Serpiente', type:'boreal', figure:'Una serpiente enroscada que sostiene el Ofiuco',
    desc:'La única constelación dividida en dos partes: Serpens Caput (cabeza) y Serpens Cauda (cola), separadas por Ofiuco.',
    stars:[[0.60,0.42],[0.62,0.40],[0.64,0.41],[0.65,0.44],[0.63,0.46],[0.61,0.44]], lines:[[0,1],[1,2],[2,3],[3,4],[4,5],[5,0]] },
  { name:'Ofiuco', alias:'El Portador de Serpientes', type:'boreal', figure:'Un sanador sujetando una serpiente gigante',
    desc:'A veces llamada "la decimotercera constelación del zodiaco". Barnard, la segunda estrella más cercana al Sol, se halla aquí.',
    stars:[[0.63,0.48],[0.65,0.46],[0.67,0.48],[0.66,0.51],[0.64,0.53],[0.68,0.52]], lines:[[0,1],[1,2],[2,3],[3,4],[4,0],[2,5],[3,5]] },
  { name:'Escudo', alias:'El Escudo de Sobieski', type:'boreal', figure:'Un escudo heráldico resplandeciente',
    desc:'Una de las constelaciones más pequeñas, creada en 1684. A pesar de su tamaño, alberga M11, la "Cúmulo del Pato Silvestre", denso y brillante.',
    stars:[[0.75,0.52],[0.77,0.50],[0.78,0.53],[0.76,0.55],[0.74,0.53]], lines:[[0,1],[1,2],[2,3],[3,4],[4,0]] },
  { name:'Sagita', alias:'La Flecha', type:'boreal', figure:'Una flecha disparada hacia el horizonte celeste',
    desc:'Una de las constelaciones más pequeñas, pero conocida desde la antigüedad. Representa la flecha de Cupido o la disparada por Hércules.',
    stars:[[0.77,0.38],[0.79,0.37],[0.81,0.37],[0.80,0.36],[0.80,0.38]], lines:[[0,1],[1,2],[1,3],[1,4]] },
  { name:'Delfín', alias:'El Delfín Saltador', type:'boreal', figure:'Un delfín saltando sobre las olas cósmicas',
    desc:'Pequeña pero reconocible constelación en forma de rombo. Sus cuatro estrellas principales se llamaron "el Ataúd de Napoleón" en el siglo XIX.',
    stars:[[0.80,0.42],[0.82,0.41],[0.83,0.43],[0.81,0.44],[0.82,0.46]], lines:[[0,1],[1,2],[2,3],[3,0],[2,4]] },
  { name:'Equuleus', alias:'El Caballito', type:'boreal', figure:'La cabeza de un pequeño caballo celeste',
    desc:'La segunda constelación más pequeña. Solo muestra la cabeza de un caballito. Ptolomeo la catalogó en el siglo II d.C.',
    stars:[[0.83,0.45],[0.85,0.44],[0.85,0.46],[0.84,0.47]], lines:[[0,1],[1,2],[2,3],[3,0]] },
  { name:'Triángulo', alias:'El Triángulo Celeste', type:'boreal', figure:'Un triángulo perfecto trazado en las estrellas',
    desc:'Pequeña constelación con forma inconfundible. M33, la galaxia del Triángulo, es el tercer miembro del Grupo Local a 2.7 millones de años luz.',
    stars:[[0.06,0.30],[0.08,0.27],[0.10,0.31]], lines:[[0,1],[1,2],[2,0]] },
  { name:'Lince', alias:'El Lince Celeste', type:'boreal', figure:'Un lince de vista aguda trepando por el norte',
    desc:'Hevelius la nombró "el Lince" porque se necesitan ojos de lince para ver sus tenues estrellas. Es la undécima constelación más grande.',
    stars:[[0.33,0.22],[0.35,0.20],[0.37,0.22],[0.36,0.25],[0.34,0.26],[0.32,0.24]], lines:[[0,1],[1,2],[2,3],[3,4],[4,5],[5,0]] },
  { name:'Leo Menor', alias:'El León Pequeño', type:'boreal', figure:'Un pequeño cachorro de león trepando al norte',
    desc:'Creada por Johannes Hevelius en 1687 con estrellas entre la Osa Mayor y Leo. Sus estrellas son todas de magnitud 4 o más tenues.',
    stars:[[0.37,0.30],[0.39,0.28],[0.41,0.30],[0.40,0.33],[0.38,0.33]], lines:[[0,1],[1,2],[2,3],[3,4],[4,0]] },
  { name:'Canes Venatici', alias:'Los Perros de Caza', type:'boreal', figure:'Dos perros de caza persiguiendo a la Osa Mayor',
    desc:'Sus dos estrellas principales representan a los perros de Asterión y Chara. M51, la galaxia del Torbellino, es la primera en que se detectó estructura espiral.',
    stars:[[0.49,0.22],[0.51,0.20],[0.52,0.24],[0.50,0.26]], lines:[[0,1],[1,2],[2,3],[3,0]] },
  { name:'Cabellera de Berenice', alias:'Los Cabellos de la Reina', type:'boreal', figure:'La melena dorada de la reina Berenice',
    desc:'Una de las pocas constelaciones nombradas por una persona histórica real. Alberga el Cúmulo de Coma, un supercúmulo de galaxias a 320 millones de años luz.',
    stars:[[0.51,0.29],[0.53,0.27],[0.55,0.29],[0.54,0.32],[0.52,0.32]], lines:[[0,1],[1,2],[2,3],[3,4],[4,0]] },
  { name:'Zorra', alias:'La Pequeña Zorra', type:'boreal', figure:'Una zorra astuta portando un ganso en la boca',
    desc:'Hevelius la creó en 1687. Aunque pequeña y tenue, alberga M27, la Nebulosa Dumbbell, la primera nebulosa planetaria descubierta (1764).',
    stars:[[0.77,0.33],[0.79,0.31],[0.80,0.33],[0.79,0.35],[0.77,0.35]], lines:[[0,1],[1,2],[2,3],[3,4],[4,0]] },
  { name:'Ceto', alias:'La Ballena Marina', type:'boreal', figure:'Un monstruo marino con fauces abiertas',
    desc:'Segunda constelación más grande del cielo. Mira, en su cuello, es una variable roja que cambia de brillo con un período de 332 días.',
    stars:[[0.05,0.46],[0.07,0.44],[0.09,0.45],[0.08,0.48],[0.06,0.50],[0.10,0.47]], lines:[[0,1],[1,2],[2,3],[3,4],[4,0],[2,5],[3,5]] },
  { name:'Eridanus', alias:'El Río Celestial', type:'boreal', figure:'Un río serpenteante que nace en Orión y fluye al sur',
    desc:'La segunda constelación más larga. Achernar, en su extremo sur, es la novena estrella más brillante del cielo. El río nace cerca de Rigel.',
    stars:[[0.24,0.48],[0.22,0.52],[0.20,0.55],[0.18,0.57],[0.16,0.55],[0.14,0.57],[0.13,0.60]], lines:[[0,1],[1,2],[2,3],[3,4],[4,5],[5,6]] },
  { name:'Monoceros', alias:'El Unicornio', type:'boreal', figure:'Un unicornio blanco galopando entre estrellas',
    desc:'Casi invisible a simple vista pero espléndida con telescopio. La Nebulosa Roseta y la Nebulosa del Cono se encuentran en sus confines.',
    stars:[[0.33,0.46],[0.35,0.44],[0.37,0.45],[0.36,0.48],[0.34,0.49],[0.38,0.48]], lines:[[0,1],[1,2],[2,3],[3,4],[4,0],[2,5],[3,5]] },

  // �"?�"? AUSTRALES �"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?�"?
  { name:'Cruz del Sur', alias:'Crux', type:'austral', figure:'Una cruz brillante que guía a los navegantes del sur',
    desc:'La más pequeña de las 88 constelaciones pero crucial para la navegación. Sus cuatro estrellas principales indican el polo sur celeste.',
    stars:[[0.45,0.52],[0.42,0.56],[0.45,0.60],[0.48,0.56],[0.43,0.54]], lines:[[0,2],[1,3],[0,4],[4,2]] },
  { name:'Centauro', alias:'El Centauro Sabio', type:'austral', figure:'Un centauro portando una lanza y una víctima',
    desc:'Contiene Alpha Centauri, el sistema estelar más cercano al Sol a 4.37 años luz. Proxima Centauri es la estrella individual más próxima.',
    stars:[[0.72,0.42],[0.75,0.45],[0.78,0.43],[0.74,0.48],[0.77,0.50],[0.80,0.48]], lines:[[0,1],[1,2],[1,3],[3,4],[4,5],[2,5]] },
  { name:'Escorpión Austral', alias:'Corona Australis', type:'austral', figure:'Una pequeña corona de laurel del hemisferio sur',
    desc:'La versión austral de la Corona Boreal. A pesar de su pequeño tamaño, es reconocible por su arco brillante de estrellas en el sur.',
    stars:[[0.71,0.68],[0.73,0.66],[0.75,0.66],[0.77,0.68],[0.75,0.70],[0.73,0.70]], lines:[[0,1],[1,2],[2,3],[3,4],[4,5],[5,0]] },
  { name:'Lupus', alias:'El Lobo Celeste', type:'austral', figure:'Un lobo atrapado por el centauro con su lanza',
    desc:'Antiguamente era considerada parte de Centauro y se llamaba "la bestia". Contiene varias estrellas brillantes y algunos cúmulos estelares notables.',
    stars:[[0.61,0.64],[0.63,0.62],[0.65,0.63],[0.64,0.66],[0.62,0.67],[0.66,0.65]], lines:[[0,1],[1,2],[2,3],[3,4],[4,0],[2,5],[3,5]] },
  { name:'Ara', alias:'El Altar', type:'austral', figure:'Un altar con fuego sagrado ofrecido a los dioses',
    desc:'Una de las 48 constelaciones de Ptolomeo. Se sitúa en la Vía Láctea con rica densidad estelar. Contiene la nebulosa NGC 6193.',
    stars:[[0.68,0.70],[0.70,0.68],[0.72,0.70],[0.71,0.73],[0.69,0.73],[0.73,0.72]], lines:[[0,1],[1,2],[2,3],[3,4],[4,0],[2,5],[3,5]] },
  { name:'Telescopio', alias:'El Telescopio', type:'austral', figure:'Un telescopio apuntando al cosmos del sur',
    desc:'Creada por Nicolas Louis de Lacaille en el siglo XVIII para honrar los instrumentos astronómicos. Sus estrellas son tenues.',
    stars:[[0.77,0.73],[0.79,0.71],[0.80,0.73],[0.79,0.76],[0.77,0.76]], lines:[[0,1],[1,2],[2,3],[3,4],[4,0]] },
  { name:'Pavo', alias:'El Pavorreal', type:'austral', figure:'Un pavorreal con la cola extendida en el sur',
    desc:'Introducida por Pieter Dirkszoon Keyser y Frederick de Houtman. Peacock, su estrella más brillante, es una de las 57 estrellas náuticas.',
    stars:[[0.79,0.78],[0.81,0.76],[0.83,0.78],[0.82,0.81],[0.80,0.81],[0.84,0.80]], lines:[[0,1],[1,2],[2,3],[3,4],[4,0],[2,5],[3,5]] },
  { name:'Microscopio', alias:'El Microscopio', type:'austral', figure:'Un microscopio científico apuntando al infinito',
    desc:'Otra creación de Lacaille para honrar instrumentos científicos. Sus estrellas son tan tenues que apenas son visibles sin óptica.',
    stars:[[0.86,0.62],[0.88,0.60],[0.89,0.62],[0.88,0.65],[0.86,0.65]], lines:[[0,1],[1,2],[2,3],[3,4],[4,0]] },
  { name:'Grulla', alias:'La Grulla Blanca', type:'austral', figure:'Una grulla con las alas extendidas en vuelo',
    desc:'Introducida por los cartógrafos holandeses. Alnair, su estrella principal, es la trigésima segunda estrella más brillante del cielo.',
    stars:[[0.88,0.68],[0.90,0.66],[0.91,0.68],[0.90,0.71],[0.88,0.72],[0.92,0.70]], lines:[[0,1],[1,2],[2,3],[3,4],[4,0],[2,5],[3,5]] },
  { name:'Fénix', alias:'El Ave Fénix', type:'austral', figure:'El ave mítica renaciendo de las llamas',
    desc:'Introducida por Keyser y De Houtman en 1598. Ankaa, su estrella principal, tiene una alta velocidad propia que la hace visible como "estrella de alta velocidad".',
    stars:[[0.93,0.74],[0.95,0.72],[0.96,0.74],[0.95,0.77],[0.93,0.77],[0.97,0.76]], lines:[[0,1],[1,2],[2,3],[3,4],[4,0],[2,5],[3,5]] },
  { name:'Escultor', alias:'El Estudio del Escultor', type:'austral', figure:'El taller de un escultor con herramientas esparcidas',
    desc:'Lacaille la bautizó en 1756. El Polo Sur de la Vía Láctea se encuentra aquí. El Grupo del Escultor es un conjunto de galaxias cercanas.',
    stars:[[0.92,0.60],[0.94,0.58],[0.95,0.60],[0.94,0.63],[0.92,0.63]], lines:[[0,1],[1,2],[2,3],[3,4],[4,0]] },
  { name:'Piscis Austral', alias:'El Pez Austral', type:'austral', figure:'Un pez solitario bebiendo el agua del Acuario',
    desc:'Fomalhaut, su estrella más brillante, fue la primera en detectársele un sistema de anillos protoplanetarios con el Hubble en 2008.',
    stars:[[0.90,0.58],[0.92,0.56],[0.93,0.58],[0.92,0.61],[0.90,0.61],[0.94,0.60]], lines:[[0,1],[1,2],[2,3],[3,4],[4,0],[2,5],[3,5]] },
  { name:'Tucana', alias:'El Tucán', type:'austral', figure:'Un tucán con pico colorido del cielo austral',
    desc:'Alberga la Pequeña Nube de Magallanes y el cúmulo globular 47 Tucanae, uno de los más brillantes. Introducida por Keyser y De Houtman.',
    stars:[[0.93,0.80],[0.95,0.78],[0.96,0.80],[0.95,0.83],[0.93,0.83],[0.97,0.82]], lines:[[0,1],[1,2],[2,3],[3,4],[4,0],[2,5],[3,5]] },
  { name:'Indio', alias:'El Indio Americano', type:'austral', figure:'Un indígena americano con lanza y plumas',
    desc:'Introducida por cartógrafos holandeses del siglo XVI. Epsilon Indi es una de las estrellas más similares al Sol en las cercanías, a 11.8 años luz.',
    stars:[[0.82,0.72],[0.84,0.70],[0.85,0.72],[0.84,0.75],[0.82,0.75],[0.86,0.74]], lines:[[0,1],[1,2],[2,3],[3,4],[4,0],[2,5],[3,5]] },
  { name:'Carina', alias:'La Quilla del Navío', type:'austral', figure:'La quilla de un poderoso barco navegante',
    desc:'Antes era parte de la enorme constelación Argo Navis, dividida en tres por Lacaille. Contiene Canopus, la segunda estrella más brillante del cielo.',
    stars:[[0.30,0.84],[0.32,0.82],[0.34,0.84],[0.33,0.87],[0.31,0.88],[0.35,0.86]], lines:[[0,1],[1,2],[2,3],[3,4],[4,0],[2,5],[3,5]] },
  { name:'Vela', alias:'Las Velas del Navío', type:'austral', figure:'Las velas llenas de viento de un barco antiguo',
    desc:'Junto con Carina y Puppis, formaba la constelación Argo Navis. Contiene el Remanente de Vela, una nebulosa resultado de una supernova ocurrida hace 11,000 años.',
    stars:[[0.36,0.78],[0.38,0.76],[0.40,0.78],[0.39,0.81],[0.37,0.82],[0.41,0.80]], lines:[[0,1],[1,2],[2,3],[3,4],[4,0],[2,5],[3,5]] },
  { name:'Popa', alias:'La Popa del Navío', type:'austral', figure:'La popa ornamentada de un antiguo galeón',
    desc:'Tercera parte de la antigua Argo Navis. Contiene la supergigante L Puppis, una de las estrellas más luminosas visibles a simple vista.',
    stars:[[0.28,0.76],[0.30,0.74],[0.32,0.76],[0.31,0.79],[0.29,0.79],[0.33,0.78]], lines:[[0,1],[1,2],[2,3],[3,4],[4,0],[2,5],[3,5]] },
  { name:'Cúmulo Austral', alias:'Musca', type:'austral', figure:'Una pequeña mosca zumbando en el sur celeste',
    desc:'La única constelación que representa un insecto. Fue introducida por Keyser y De Houtman. Contiene NGC 4833, un cúmulo globular cercano.',
    stars:[[0.50,0.76],[0.52,0.74],[0.53,0.76],[0.52,0.79],[0.50,0.79]], lines:[[0,1],[1,2],[2,3],[3,4],[4,0]] },
  { name:'Norma', alias:'La Escuadra del Carpintero', type:'austral', figure:'Una escuadra y regla de herrero celeste',
    desc:'Creada por Lacaille para representar herramientas. Se ubica en la Vía Láctea y alberga el Cúmulo Abierto NGC 6067 con muchas variables cefeidas.',
    stars:[[0.62,0.74],[0.64,0.72],[0.65,0.74],[0.64,0.77],[0.62,0.77]], lines:[[0,1],[1,2],[2,3],[3,4],[4,0]] },
  { name:'Compás', alias:'Circinus', type:'austral', figure:'Un compás de navegante en el cielo austral',
    desc:'Pequeña constelación al sur del Centauro. Alberga Alpha Circini, una estrella variable del tipo roAp, y la Galaxia del Compás NGC 5128.',
    stars:[[0.65,0.80],[0.67,0.78],[0.68,0.80],[0.67,0.83]], lines:[[0,1],[1,2],[2,3],[3,0]] },
  { name:'Triángulo Austral', alias:'El Triángulo del Sur', type:'austral', figure:'Un triángulo celestial en el cielo austral',
    desc:'Fácilmente reconocible por sus tres estrellas brillantes. Es la 83ª constelación en tamaño pero sus estrellas son más brillantes que las del Triángulo boreal.',
    stars:[[0.68,0.78],[0.70,0.75],[0.72,0.78]], lines:[[0,1],[1,2],[2,0]] },
  { name:'Ave del Paraíso', alias:'Apus', type:'austral', figure:'Un exótico ave del paraíso con plumaje colorido',
    desc:'Introducida por Keyser y De Houtman, la constelación representa el Ave del Paraíso traída de Nueva Guinea. Sus estrellas son relativamente tenues.',
    stars:[[0.73,0.84],[0.75,0.82],[0.76,0.84],[0.75,0.87],[0.73,0.87]], lines:[[0,1],[1,2],[2,3],[3,4],[4,0]] },
  { name:'Octante', alias:'El Octante del Sur', type:'austral', figure:'Un octante, instrumento de navegación del siglo XVIII',
    desc:'La constelación más austral, contiene el polo sur celeste (no hay estrella polar brillante en el sur). El polo sur celeste está a 1° de Sigma Octantis.',
    stars:[[0.60,0.90],[0.62,0.88],[0.64,0.90],[0.63,0.93],[0.61,0.93]], lines:[[0,1],[1,2],[2,3],[3,4],[4,0]] },
  { name:'Hidrus', alias:'La Serpiente de Agua', type:'austral', figure:'Una serpiente acuática del cielo del sur',
    desc:'No confundir con Hidra. Contiene Beta Hydri, la estrella más cercana al polo sur celeste visible a simple vista. Muy cercana al sol en sus propiedades.',
    stars:[[0.02,0.86],[0.04,0.84],[0.05,0.87],[0.04,0.90],[0.02,0.90]], lines:[[0,1],[1,2],[2,3],[3,4],[4,0]] },
  { name:'Tucana Austral', alias:'Dorado', type:'austral', figure:'Un pez dorado brillando en el profundo sur',
    desc:'Alberga la Gran Nube de Magallanes, una galaxia satélite de la Vía Láctea a solo 163,000 años luz. S Doradus es una de las estrellas más luminosas conocidas.',
    stars:[[0.09,0.84],[0.11,0.82],[0.12,0.84],[0.11,0.87],[0.09,0.87]], lines:[[0,1],[1,2],[2,3],[3,4],[4,0]] },
  { name:'Red', alias:'Reticulum', type:'austral', figure:'Un retículo o mira de un instrumento óptico',
    desc:'Lacaille la creó como "el Retículo Romboidal" en honor al instrumento óptico. R Reticuli es una estrella variable Mira muy roja.',
    stars:[[0.13,0.88],[0.15,0.86],[0.16,0.89],[0.14,0.91]], lines:[[0,1],[1,2],[2,3],[3,0]] },
  { name:'Pintor', alias:'El Caballete del Pintor', type:'austral', figure:'Un caballete de pintor con lienzo en blanco',
    desc:'Creada por Lacaille en honor a la paleta y el caballete del pintor. Alpha Pictoris tiene un disco circumestelar que fue detectado en la primera imagen directa de tal estructura.',
    stars:[[0.22,0.82],[0.24,0.80],[0.25,0.83],[0.24,0.86],[0.22,0.86]], lines:[[0,1],[1,2],[2,3],[3,4],[4,0]] },
  { name:'Volador', alias:'Volans', type:'austral', figure:'Un pez volador saltando entre las estrellas',
    desc:'Introducida por Keyser y De Houtman. Representa el pez volador que acompañaba al gran barco de Argo en sus viajes. Sus estrellas son relativamente tenues.',
    stars:[[0.27,0.86],[0.29,0.84],[0.30,0.86],[0.29,0.89],[0.27,0.89]], lines:[[0,1],[1,2],[2,3],[3,4],[4,0]] },
  { name:'Camaleón', alias:'El Camaleón', type:'austral', figure:'Un camaleón con piel cambiante en el polo sur',
    desc:'Introducida por Keyser y De Houtman en 1598. Está rodeada por la gran nebulosa Eta Carinae y por la Gran Nube de Magallanes.',
    stars:[[0.40,0.90],[0.42,0.88],[0.44,0.90],[0.43,0.93],[0.41,0.93]], lines:[[0,1],[1,2],[2,3],[3,4],[4,0]] },
  { name:'Mesa', alias:'Mensa', type:'austral', figure:'La montaña Table Mountain de Ciudad del Cabo',
    desc:'La única constelación nombrada por una característica geográfica terrestre. Lacaille la creó en honor a la Montaña de la Mesa en Ciudad del Cabo donde realizó sus observaciones.',
    stars:[[0.34,0.90],[0.36,0.88],[0.37,0.91],[0.36,0.94],[0.34,0.94]], lines:[[0,1],[1,2],[2,3],[3,4],[4,0]] },
  { name:'Hidra', alias:'La Gran Hidra de Agua', type:'austral', figure:'Una enorme serpiente de agua sinuosa',
    desc:'La constelación más extensa del cielo, ocupando 3.2% de la esfera celeste. Su estrella principal Alphard significa "el solitario" en árabe.',
    stars:[[0.40,0.56],[0.42,0.54],[0.44,0.56],[0.43,0.59],[0.41,0.60],[0.46,0.58],[0.45,0.62]], lines:[[0,1],[1,2],[2,3],[3,4],[4,0],[2,5],[3,6],[5,6]] },
  { name:'Cuervo', alias:'El Cuervo Negro', type:'austral', figure:'Un cuervo negro posado sobre la Hidra',
    desc:'Reconocible cuadrilátero de cuatro estrellas. En la mitología griega, el cuervo fue enviado por Apolo a buscar agua pero se entretuvo en una higuera.',
    stars:[[0.50,0.62],[0.52,0.60],[0.54,0.62],[0.53,0.65],[0.51,0.65]], lines:[[0,1],[1,2],[2,3],[3,4],[4,0]] },
  { name:'Copa', alias:'La Copa de Apolo', type:'austral', figure:'Un cáliz o copa de vino de los dioses',
    desc:'Ubicada entre Hidra y Cuervo. La mitología dice que el cuervo llevaba esta copa cuando fue distraído, explicando por qué llegó tarde ante Apolo.',
    stars:[[0.46,0.60],[0.48,0.58],[0.49,0.60],[0.48,0.63],[0.46,0.63]], lines:[[0,1],[1,2],[2,3],[3,4],[4,0]] },
  { name:'Horno', alias:'Fornax', type:'austral', figure:'Un horno de laboratorio científico',
    desc:'Lacaille la creó para representar el horno químico. Alberga el Cúmulo del Horno, un conjunto de galaxias a 60 millones de años luz.',
    stars:[[0.12,0.74],[0.14,0.72],[0.15,0.74],[0.14,0.77],[0.12,0.77]], lines:[[0,1],[1,2],[2,3],[3,4],[4,0]] },
  { name:'Reloj', alias:'Horologium', type:'austral', figure:'Un reloj de péndulo marcando el tiempo cósmico',
    desc:'Lacaille la creó en 1756 para representar el reloj de péndulo, instrumento clave en astronomía de su época. Sus estrellas son muy tenues.',
    stars:[[0.08,0.76],[0.10,0.74],[0.11,0.76],[0.10,0.79],[0.08,0.79]], lines:[[0,1],[1,2],[2,3],[3,4],[4,0]] },
  { name:'Escultor Austral', alias:'Caelum', type:'austral', figure:'El buril del escultor grabando en piedra celeste',
    desc:'Creada por Lacaille, es la quinta constelación más pequeña. Representa un cincel de grabador. Sus estrellas son demasiado tenues para ser vistas a simple vista.',
    stars:[[0.04,0.78],[0.06,0.76],[0.07,0.79],[0.05,0.81]], lines:[[0,1],[1,2],[2,3],[3,0]] },
  { name:'Paloma', alias:'Columba', type:'austral', figure:'Una paloma mensajera volando hacia el Arca de Noé',
    desc:'Phact, su estrella principal, se mueve a gran velocidad a través del espacio, siendo quizás expulsada de una explosión de supernova hace millones de años.',
    stars:[[0.20,0.76],[0.22,0.74],[0.24,0.76],[0.23,0.79],[0.21,0.79],[0.25,0.78]], lines:[[0,1],[1,2],[2,3],[3,4],[4,0],[2,5],[3,5]] },
  { name:'Liebre', alias:'Lepus', type:'austral', figure:'Una liebre veloz huyendo del cazador Orión',
    desc:'Ubicada a los pies de Orión, la liebre que el cazador persigue. Contiene la Nebulosa de la Burbuja, muy llamativa con telescopio.',
    stars:[[0.24,0.58],[0.26,0.56],[0.28,0.57],[0.27,0.60],[0.25,0.61],[0.29,0.60]], lines:[[0,1],[1,2],[2,3],[3,4],[4,0],[2,5],[3,5]] },
  { name:'Perro Mayor', alias:'Canis Major', type:'austral', figure:'El perro fiel del cazador Orión con Sirio como nariz',
    desc:'Contiene Sirio, la estrella más brillante del cielo nocturno. Los egipcios usaban su salida heliaca para predecir las crecidas del Nilo.',
    stars:[[0.24,0.68],[0.26,0.66],[0.28,0.67],[0.27,0.70],[0.25,0.71],[0.29,0.70]], lines:[[0,1],[1,2],[2,3],[3,4],[4,0],[2,5],[3,5]] },
  { name:'Perro Menor', alias:'Canis Minor', type:'boreal', figure:'El fiel perrito de Orión siguiendo su rastro',
    desc:'Contiene Proción, la octava estrella más brillante del cielo, a solo 11.5 años luz. Forma el vértice inferior del Triángulo de Invierno.',
    stars:[[0.32,0.44],[0.34,0.42],[0.35,0.44],[0.33,0.46]], lines:[[0,1],[1,2],[2,3],[3,0]] },
  { name:'Sextante', alias:'El Sextante Náutico', type:'boreal', figure:'Un sextante de navegación midiendo el cosmos',
    desc:'Creada por Hevelius en 1687 en honor al sextante que usaba para medir posiciones estelares. Sus estrellas son muy tenues y difíciles de ver.',
    stars:[[0.40,0.48],[0.42,0.46],[0.43,0.48],[0.42,0.51],[0.40,0.51]], lines:[[0,1],[1,2],[2,3],[3,4],[4,0]] },
  { name:'Antlia', alias:'La Bomba de Aire', type:'austral', figure:'Una bomba de vacío del siglo XVIII',
    desc:'Lacaille la creó para representar la bomba de vacío inventada por Boyle. Es una de las constelaciones más tenues y poco distinguibles del cielo.',
    stars:[[0.41,0.70],[0.43,0.68],[0.44,0.70],[0.43,0.73],[0.41,0.73]], lines:[[0,1],[1,2],[2,3],[3,4],[4,0]] },
  { name:'Brújula', alias:'Pyxis', type:'austral', figure:'La brújula náutica del Argo',
    desc:'Cuarta parte de la antigua Argo Navis, aunque Lacaille la trató independientemente. Alberga T Pyxidis, una nova recurrente que explota aproximadamente cada 20 años.',
    stars:[[0.35,0.74],[0.37,0.72],[0.38,0.74],[0.37,0.77],[0.35,0.77]], lines:[[0,1],[1,2],[2,3],[3,4],[4,0]] },
]

export const chapters = [
  {
    id: 1,
    label: 'Capítulo I',
    title: 'Orígenes del Universo',
    text: 'Hace 13.800 millones de años, toda la materia, energía, espacio y tiempo surgieron de una singularidad infinitesimalmente pequeña. El Big Bang no fue una explosión en el espacio �?" fue la expansión del espacio mismo. En fracciones de segundo, el universo pasó de ser más pequeño que un átomo a tener millones de kilómetros.',
    tags: ['Big Bang', 'Inflación Cósmica', 'Primeras Estrellas', 'Materia Oscura'],
    image: 'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=600&h=400&fit=crop',
    puzzle: { type: 'order' as const, question: 'Ordena los eventos del Big Bang desde el inicio', items: ['Singularidad', 'Inflación', 'Quarks y Leptones', 'Núcleos atómicos', 'Primeras estrellas'] },
  },
  {
    id: 2,
    label: 'Capítulo II',
    title: 'Nacimiento de Galaxias',
    text: 'La materia oscura actuó como andamio gravitacional, atrayendo gas hidrógeno hacia estructuras filamentosas. En los nodos de esta red cósmica, las galaxias comenzaron a formarse hace 13.000 millones de años. Colisiones y fusiones moldearon su evolución hasta crear espirales, elípticas y galaxias irregulares.',
    tags: ['Materia Oscura', 'Formación Galáctica', 'Vía Láctea', 'Evolución Estelar'],
    image: 'https://images.unsplash.com/photo-1543722530-d2c3201371e7?w=600&h=400&fit=crop',
    puzzle: { type: 'quiz' as const, question: '¿Qué tipo de galaxia es la Vía Láctea?', options: ['Elíptica', 'Espiral barrada', 'Irregular', 'Lenticular'], answer: 1 },
  },
  {
    id: 3,
    label: 'Capítulo III',
    title: 'Nuestro Sistema Solar',
    text: 'Hace 4.600 millones de años, una nube molecular gigante colapsó bajo su propia gravedad. El 99.86% de la masa se concentró en el Sol, mientras los restos formaron un disco protoplanetario. Por acreción, pequeñas partículas se unieron formando planetesimales y finalmente los ocho planetas que conocemos.',
    tags: ['Formación Solar', 'Acreción Planetaria', 'Migración Orbital', 'Disco Protoplanetario'],
    image: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=600&h=400&fit=crop',
    puzzle: { type: 'match' as const, question: 'Conecta cada planeta con su característica', pairs: [['Mercurio', 'Más cercano al Sol'], ['Júpiter', 'El más grande'], ['Saturno', 'Anillos visibles'], ['Neptuno', 'Vientos más rápidos']] },
  },
  {
    id: 4,
    label: 'Capítulo IV',
    title: 'Teorías Modernas',
    text: 'La física moderna ha revelado que el 95% del universo es invisible: 27% materia oscura y 68% energía oscura. Los agujeros negros supermasivos habitan el centro de cada galaxia. La teoría del multiverso sugiere que nuestro universo podría ser uno entre infinitos.',
    tags: ['Multiverso', 'Energía Oscura', 'Agujeros Negros', 'Ondas Gravitacionales'],
    image: 'https://images.unsplash.com/photo-1419242902214-272b3f66ee7a?w=600&h=400&fit=crop',
    puzzle: { type: 'truefalse' as const, question: 'Responde verdadero o falso a cada afirmación', statements: [{ text: 'La materia oscura compone el 68% del universo', answer: false }, { text: 'Los agujeros negros supermasivos están en el centro de cada galaxia', answer: true }, { text: 'La materia visible compone menos del 5% del universo', answer: true }] },
  },
  {
    id: 5,
    label: 'Capítulo V',
    title: 'Destino del Universo',
    text: 'La expansión acelerada del universo plantea escenarios fascinantes. El Big Freeze predice un universo frío donde las estrellas se apagan. El Big Rip desgarraría incluso los átomos. El Big Crunch revertería la expansión en un gran colapso. ¿Cuál será el destino final del cosmos?',
    tags: ['Big Freeze', 'Big Crunch', 'Big Rip', 'Entropía Máxima'],
    image: 'https://images.unsplash.com/photo-1454789548928-9efd52dc4031?w=600&h=400&fit=crop',
    puzzle: { type: 'quiz' as const, question: '¿Qué escenario predice que la expansión del universo desgarrará incluso los átomos?', options: ['Big Freeze', 'Big Crunch', 'Big Rip', 'Big Bounce'], answer: 2 },
  },
]

export const missions = [
  {
    title: 'Europa Clipper',
    desc: 'Exploración de la luna Europa de Júpiter, buscando condiciones para la vida bajo su océano helado de 100 km de profundidad.',
    status: 'EN TRÁNSITO',
    active: true,
    icon: 'globe',
    color: 'cyan',
    chapter: 3,
  },
  {
    title: 'Parker Solar Probe',
    desc: 'La nave más cercana al Sol, estudiando la corona solar y el viento solar a distancias sin precedentes.',
    status: 'ACTIVO',
    active: true,
    icon: 'star',
    color: 'gold',
    chapter: 3,
  },
  {
    title: 'Dragonfly',
    desc: 'Un dron explorador volará sobre Titán, la luna de Saturno, buscando química prebiótica en sus lagos de metano.',
    status: 'LANZAMIENTO 2028',
    active: false,
    icon: 'rocket',
    color: 'purple',
    chapter: 3,
  },
  {
    title: 'James Webb',
    desc: 'El telescopio más poderoso jamás construido observa las primeras galaxias formadas tras el Big Bang.',
    status: 'ACTIVO',
    active: true,
    icon: 'telescope',
    color: 'rose',
    chapter: 2,
  },
  {
    title: 'LISA Pathfinder',
    desc: 'Precursor del detector de ondas gravitacionales espacial que revolucionará nuestra comprensión del cosmos.',
    status: 'EN DESARROLLO',
    active: false,
    icon: 'wave',
    color: 'emerald',
    chapter: 4,
  },
  {
    title: 'Voyager 1 & 2',
    desc: 'Las naves más lejanas de la humanidad, navegando el espacio interestelar a más de 23 mil millones de km del Sol.',
    status: 'INTERESTELAR',
    active: true,
    icon: 'satellite',
    color: 'indigo',
    chapter: 5,
  },
]

export const galleryImages = [
  { src: 'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=500&h=350&fit=crop', alt: 'Nebulosa del Águila' },
  { src: 'https://images.unsplash.com/photo-1419242902214-272b3f66ee7a?w=500&h=350&fit=crop', alt: 'Campo Estelar Profundo' },
  { src: 'https://images.unsplash.com/photo-1614732414444-096e5f1122d5?w=500&h=350&fit=crop', alt: 'Saturno y sus Anillos' },
  { src: 'https://images.unsplash.com/photo-1543722530-d2c3201371e7?w=500&h=350&fit=crop', alt: 'Vía Láctea' },
  { src: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=500&h=350&fit=crop', alt: 'Tierra desde el Espacio' },
  { src: 'https://images.unsplash.com/photo-1454789548928-9efd52dc4031?w=500&h=350&fit=crop', alt: 'Astronauta en EVA' },
  { src: 'https://images.unsplash.com/photo-1516339901601-2e1b62dc0c45?w=500&h=350&fit=crop', alt: 'Nebulosa de Carina' },
]

